/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:32854eb2-2feb-46f4-9614-59a08b71f663",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xj7CP2l1r",
    "aws_user_pools_web_client_id": "5q30ve9js30fdnl04gquli4fqu",
    "oauth": {}
};


export default awsmobile;
